title: SystemVerilog Engineering Log
author: Art Kulakevich
description: hello world!

# Remote Theme Configuration
remote_theme: jekyll/minima

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
